import React, { useRef } from 'react';
import Head from 'next/head';
import domtoimage from 'dom-to-image';

const Autostory = ({ productData }) => {
  const containerRef = useRef();

  const handleDownloadImage = () => {
    const element = containerRef.current;

    if (element) {
      const imageElement = element.querySelector('.image-container img');
      const originalSrc = imageElement.src; // Store the original src

      // Set the src attribute to the imgSrc URL
      imageElement.src = productData.imgSrc;

      // Remove unnecessary elements before taking the screenshot
      const elementsToRemove = element.querySelectorAll('.remove-on-screenshot');
      elementsToRemove.forEach(element => element.remove());

      domtoimage.toPng(element)
        .then(function (dataUrl) {
          var link = document.createElement('a');
          link.href = dataUrl;
          link.download = 'product-story.png';
          link.click();
          imageElement.src = originalSrc; // Restore the original src
        })
        .catch(function (error) {
          console.error('Error:', error);
          imageElement.src = originalSrc; // Restore the original src in case of an error
        });
    } else {
      console.error('autostory-container elementi bulunamadı.');
    }
  };

  return (
    <div id='autostory-container'>
      <Head>
        <title>MY PROJECT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row-2 min-h-screen items-center justify-center">
        <div
          className="relative h-[800px] w-[400px] "
          ref={containerRef}
          style={{ background: 'transparent' }}
        >
          <div className="h-full w-full bg-[100%] bg-gradient-to-r from-yellow-200  to-pink-500 ... " />
          <div className="absolute top-12 m-12 h-9/16 w-3/4 flex flex-col rounded-xl bg-white bg-opacity-80 shadow">
            <div className="pl-0 pt-6 relative overflow-hidden bg-cover bg-no-repeat rounded image-container">
              {productData && (
                <img
                  className="rounded-lg mx-6"
                  src={productData.imgSrc}
                  alt={productData.name}
                  width={250}
                  height={200}
                />
              )}
            </div>
            <div className="m-2 text-center">
              <p className="text-center uppercase ">
                {productData && (
                  <>
                    <br />{productData.name}<br />
                  </>
                )}
                {productData && (
                  <>
                    <p className='text-xl uppercase font-semibold'>  {productData.website} </p>
                  </>
                )}
              </p>
              <div className='m-5'>
                {productData && productData.price && (
                  <p className="text-3xl text-purple-700 font-extrabold font-barlow">TRY{productData.price}<span className="text-"></span></p>
                )}
              </div>
              <div className='container translate-y-2/3 pl-7 absolute'>
                <img src='/logo.webp' alt='logo' width={200} height={100} />
              </div>
            </div>
          </div>
        </div>
        <div style={{ position: 'fixed', bottom: 'calc(5px + 100%)', left: '50%', transform: 'translateX(-50%)', marginBottom: '5px' }}>
    <button
      onClick={handleDownloadImage}
      style={{
        background: '#311b92',
        color: 'white',
        border: 'none',
        padding: '10px',
        fontSize: '1rem',
        cursor: 'pointer',
        borderRadius: '4px',
        width: containerRef.current && `${containerRef.current.offsetWidth}px`
      }}
    >
      İndir
    </button>
</div>

      </div>
    </div>
  )
};

export default Autostory;
