/* eslint-disable react/jsx-no-undef */
import React from 'react'


import Head from 'next/head'
import Image from 'next/image'

const autostory = () => {
  return (
    <div className='flex justify-center m-10'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
  {/* component */}
  <div className="flex  flex-row-2 min-h-screen items-center justify-center">
    <div className="relative h-[750px] w-[400px]  ">
      <div
        className="h-full w-full bg-[100%] bg-gradient-to-r from-yellow-200  to-pink-500 ... "
       
      />

      <div className="absolute  top-12 m-12 h-9/16 w-3/4 flex flex-col rounded-xl bg-white bg-opacity-80 shadow" >

      
       
      <div class="  pl-4 pt-6 relative overflow-hidden bg-cover bg-no-repeat rounded">
    <img
      class="rounded-lg"
      src="https://www.sephora.com.tr/dw/image/v2/BCZG_PRD/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw3850789e/images/hi-res/SKU/SKU_1522/517720_swatch.jpg?sw=265&sh=265&sm=fit"
      alt="lipstick" />
  </div>
  
  <div class="m-5 text-center">
    <p class="text-center font- ">
      MILK MAKEUP LIP +CHEEK <br /><b>SEPHORA</b><br />
    </p>

    
  <div className='m-5'> 
  <p class= "text-3xl text-purple-700 font-extrabold font-barlow">₪<span class="text-">138</span></p>
  </div>
  <div className='container translate-y-2/3 pl-7 absolute '>
    
    <img src='/logo.webp' alt='logo' width={200} height={100}/>
    
    </div>
  </div>
    
   </div>
   
      </div>
    
    </div>
  
</>
      
    </div>
  )
}

export default autostory